export default {
  'gcox_otc': {
    'P2P_swop': 'P2P交换',
    'max': '最大值',
    'you_want': '您想要 <span class="{0}">{1}</span> {2} ？',
    // 'buy': '购买',
    // 'sell': '出售',
    'build': '创建您的{0}广告',
    'sell_price': '售价',
    'buy_price': '买价',
    'now_buy': '立即购买',
    'now_sell': '立即出售',
    // 'otc_describe': 'OTC是一个强大而无缝的交易平台，可以连接法定和加密的世界。',
    // 'otc_app': 'OTC移动应用程序',
    // 'when_where': '无论何时何地交易！',
    'want': '想要{0}',
    'better_price': '想要更好的价格？',
    // 'get_cny_in_china': '卖比特币通过中国在中国到huzhengguo获得CNY',
    'advertising_details': '广告详情',
    'pay_to': '付给',
    'limit_number': '限制数量',
    'payment_method': '付款方式',
    'address': '地点',
    'pay_window': '付款窗口',
    'base': '基本',
    'detail': '详细',
    'i_want': '我想要',
    'new_advertising': '创建新的广告',
    'control_panel': '控制面板',
    'overall': '总体',
    'P2P_deal': 'P2P交易',
    'your_sell_advertising': '你的销售广告',
    'your_buy_advertising': '你的购买广告',
    'appraisement': '估计资产价值',
    'you_advertising': '你的广告',
    // 'show_all_symbol': '显示所有货币',
    'fee': '存款费用',
    'explain': '此押金地址只接受{0}。不要发送其他硬币。',
    // 'symbol_address': '比特币地址',
    'tow_v': '两步验证',
    'google_tip': '帳戶安全等級{0}: 两步验证是<span class="{1}">{2}</span>',
    'star_use': '启用',
    // 'vote': '通知',
    // 'email_message': '邮件通知',
    // 'tell_message': '电话通知',
    // 'new_deal': '有一个新交易',
    // 'deal_change': '交易状态已更改',
    // 'deal_msg': '交易消息',
    // 'deal_pay': '交易已付款',
    // 'daily_rate': '订阅每日价格',
    'change_tell': '更改电话号码',
    // 'user_state': '账户状态',
    // 'no_submit': '没有提交',
    // 'update_file': '上传文件',
    'does': '已成交',
    'success_deal': '成功的交易数',
    'dif_pat': '不同的合作伙伴数量',
    // 'back_score': '反馈评分',
    'user_build_time': '帐户创建',
    'last_login': '最后一次露面',
    'kyc_idcard': '身份和居住证明',
    'peer_authentication': '同行认证',
    'new_buyer': '新买家',
    'arrears_goods': '滞销货',
    'block_account': '封锁这个账号',
    'not_advertising': '没有找到广告',
    'buy_form': '购买{0}从',
    'sell_to': '出售{0}至',
    'back_communications': '回传讯{0}',
    'no_communications': '没有反馈',
    'pay_way': '付款方式',
    'invite': '邀请',
    'buy_number': '购买数量',
    'sell_number': '出售数量',
    'pay_info': '付款信息',
    // 'get_money_info': '收款信息',
    // 'bank_transfer': '银行转账',
    // 'add': '添加',
    'bank_name': '银行名称',
    // 'bank_card_id': '银行账号',
    'bank_user': '银行户名',
    'redeme': '{0}中1 {1}的价格',
    // 'radio_market': '这是目前Bitstamp {0}率的{1}价格（{2}）。 <br/>当Bitstamp {0}率变化时，价格将波动。',

    'add_phone': '添加手机号',
    'unbind_phone': '手机解绑',
    // 'next': '继续',
    'input_sms': '验证码已发送至您的手机，请在下面输入您的验证码',
    'back': '后退',
    'no_bind_mobile': '未绑定手机',
    'others': '其他要求',
    'total': '总金额',
    'add_bankcard': '新增银行卡',
    // 'update': '修改',
    // 'delete': '删除',
    'amount_emit': '数量不能为空或0',
    'not_buy_myself': '不可以买卖自己发布的广告',
    'delete_bank_card': '是否删除该银行卡？',
    'update_phone': '修改电话号码',
    'order_text': '你正在 <span class="f-c-green">购买</span><span class="green_bg">{0} {1} </span>  从 {2} 卖家的代币已被锁定，此交易已担保，请把款项支付给卖家，并在下面确认。',
    'time_out': '当付款时间过期是交易会被取消，我们将把资金退还给卖家',
    'order_sell': '你正在 <span class="red">卖出</span> <span class="green_bg">{0} {1}</span>， 代币已被平台锁定，此交易已担保，请耐心等待买家付款。',
    'complaint_list': '申诉记录',
    'complaint_id': '申诉编号',
    'complaint_type': '申诉类型',
    'complaint_cont': '申诉内容',
    'complaint_status': '申诉状态',
    'complaint_results': '申诉结果',
    'cancel_not_pay': '您已经取消了该笔交易，请勿付款！',

    'card_repetition': '银行卡重复',
    'residue_pay_time': '剩余支付时间',
    'default': '设为默认',
    'remain_count': '剩余数量',
    'currency_way': '收款方式',
    'not_need_memo': '不需要MEMO',
    'memo_address_use': 'MEMO和地址同时使用采用充值成功',
    'send_msg_to': '发送信息给 {0}',
    'bind_mobile': '请先绑定手机号',

    'create_ad': '创建广告',

    'delect_ad_affirm': '是否要删除此条广告',
    'rank': '级别'
  }
}
