export default {
  'gcox_otc': {
    'P2P_swop': 'P2P交换',
    'max': '最大值',
    'you_want': '您想要 <span class="{0}">{1}</span> {2} ？',
    'buy': '购买',
    'sell': '出售',
    'build': '创建您的{0}广告',
    'sell_price': '售价',
    'buy_price': '买价',
    'now_buy': '立即购买',
    'now_sell': '立即出售',
    'otc_describe': 'OTC是一个强大而无缝的交易平台，可以连接法定和加密的世界。',
    'otc_app': 'OTC移动应用程序',
    'when_where': '无论何时何地交易！',
    'want': '想要{0}',
    'better_price': '想要更好的价格？',
    'get_cny_in_china': '卖比特币通过中国在中国到huzhengguo获得CNY',
    'advertising_details': '广告详情',
    'pay_to': '付给',
    'limit_number': '限制数量',
    'payment_method': '付款方式',
    'address': '地点',
    'pay_window': '付款窗口',
    'base': '基本',
    'detail': '详细',
    'i_want': '我想要',
    'new_advertising': '创建新的广告',
    'control_panel': '控制面板',
    'overall': '总体',
    'P2P_deal': 'P2P交易',
    'your_sell_advertising': '你的销售广告',
    'your_buy_advertising': '你的购买广告',
    'appraisement': '估计资产价值',
    'you_advertising': '你的广告',
    'show_all_symbol': '显示所有货币',
    'fee': '存款费用',
    'explain': '此押金地址只接受{0}。不要发送其他硬币。',
    'symbol_address': '比特币地址',
    'tow_v': '两步验证',
    'google_tip': '帳戶安全等級{0}: 两步验证是<span class="{1}">{2}</span>',
    'star_use': '启用',
    'vote': '通知',
    'email_message': '邮件通知',
    'tell_message': '电话通知',
    'new_deal': '有一个新交易',
    'deal_change': '交易状态已更改',
    'deal_msg': '交易消息',
    'deal_pay': '交易已付款',
    'daily_rate': '订阅每日价格',
    'change_tell': '更改电话号码',
    'user_state': '账户状态',
    'no_submit': '没有提交',
    'update_file': '上传文件',
    'does': '已成交',
    'success_deal': '成功的交易数',
    'dif_pat': '不同的合作伙伴数量',
    'back_score': '反馈评分',
    'user_build_time': '帐户创建',
    'last_login': '最后一次露面',
    'kyc_idcard': '身份和居住证明',
    'peer_authentication': '同行认证',
    'new_buyer': '新买家',
    'arrears_goods': '滞销货',
    'block_account': '封锁这个账号',
    'not_advertising': '没有找到广告',
    'buy_form': '购买{0}从',
    'sell_to': '出售{0}至',
    'back_communications': '回传讯{0}',
    'no_communications': '没有反馈',
    'pay_way': '付款方式',
    'invite': '邀请',
    'buy_number': '购买数量',
    'sell_number': '出售数量',
    'pay_info': '付款信息',
    'get_money_info': '收款信息',
    'bank_transfer': '银行转账',
    'add': '添加',
    'bank_name': '银行名称',
    'bank_card_id': '银行账号',
    'bank_user': '银行户名',
    'redeme': '{0}中1 {1}的价格',
    'radio_market': '这是目前Bitstamp {0}率的{1}价格（{2}）。 <br/>当Bitstamp {0}率变化时，价格将波动。',

    'add_phone': '添加手机号',
    'unbind_phone': '手机解绑',
    'next': '继续',
    'input_sms': '验证码已发送至您的手机，请在下面输入您的验证码',
    'back': '后退',
    'no_bind_mobile': '未绑定手机',
    'others': '其他要求',
    'total': '总金额',
    'add_bankcard': '新增银行卡',
    'update': '修改',
    'delete': '删除',
    'amount_emit': '数量不能为空或0',
    'not_buy_myself': '不可以买卖自己发布的广告',
    'delete_bank_card': '是否删除该银行卡？',
    'update_phone': '修改电话号码',
    'order_text': '你正在 <span class="f-c-green">购买</span><span class="green_bg">{0} {1} </span>  从 {2} 卖家的代币已被锁定，此交易已担保，请把款项支付给卖家，并在下面确认。',
    'time_out': '当付款时间过期是交易会被取消，我们将把资金退还给卖家',
    'order_sell': '你正在 <span class="red">卖出</span> <span class="green_bg">{0} {1}</span>， 代币已被平台锁定，此交易已担保，请耐心等待买家付款。',
    'complaint_list': '申诉记录',
    'complaint_id': '申诉编号',
    'complaint_type': '申诉类型',
    'complaint_cont': '申诉内容',
    'complaint_status': '申诉状态',
    'complaint_results': '申诉结果',
    'cancel_not_pay': '您已经取消了该笔交易，请勿付款！',
    'card_repetition': '银行卡重复'

  },
  'login_register': {
    'Next_step': '下一步',
    'Already_registered_Login': '已有{0}账号，请登录',
    'login': '登录',
    'bitark_service': '{0}服务条款',
    'confirm_password': '确认密码',
    'Retrieve_password': '找回密码',
    'password': '请输入密码',
    'register_by_email': '邮箱注册',
    'email_account': '请输入邮箱账号',
    'KOAll': 'K.O.ALL',
    'acText_1': '账户激活邮件已经发送至',
    'acText_3': '如果您未在收件箱看到来自{0}的邮件，请再确认一下垃圾邮件。',
    'acWelcome': '欢迎致辞',
    'acText_2': '请打开邮件并点击里面提供的链接来激活您的账户。',
    'title_login': '欢迎来到{0}',
    'warm_prompt': '请确认您正在访问：',
    'Mail_sent_successfully': '邮件发送成功',
    'acText_4': '如未收到账户激活邮件，请点击下面的按钮重新发送',
    'email': '请输入邮箱',
    'ucenter': '个人信息中心',
    'retrieved_by_email': '邮箱找回',
    'register_by_cellphone': '手机注册',
    'valid_email_account': '请输入正确的邮箱账号',
    'verify_code': '请输入验证码',
    'please_reset_password': '请前往邮箱重置密码',
    'gcoxPWReg': '密码至少8位，包括大、小写字母、数字及以下特殊字符 !@#$%^&*+=',
    'retrieved_by_cellphone': '手机找回',
    'acResend': '重新发送账户激活邮件',
    'kyc_verification': 'KYC认证',
    'findPwdTip': '提交之后，您会收到一封关于如何重置密码的说明邮件',
    'confirm_new_password': '确认新密码',
    'forget_password': '忘记密码',
    'inputGoogleAuthCode': '请输入谷歌验证码',
    'agree_Service': '我已阅读并同意',
    'register': '注册'
  },
  'account': {
    'user_center_account': '账号',
    'user_center_Google_verification_code': '谷歌验证码',
    'estimated_value_coin': '币种',
    'estimated_value_withdrawal': '提现',
    'estimated_value_available': '可用余额',
    'user_Pick_up_address': '提现地址',
    'user_Draw_the_number': '提现数量',
    'user_submit': '提交',
    'user_minimum_number_of_cash': '最小提现数量为{0}。',
    'user_complete': '完成',
    'user_uncompleted': '未完成',

    "user_center_SMS_code":"短信验证码",
  },
  'exchange': {
    'exchange_password': '密码',
    'exchange_Email_format_error': '邮箱格式错误',
    'otc_exchange_Trading_limits': '交易限额',
    'otc_exchange_ask': '单价',
    'exchange_type': '类型',
    'exchange_amount': '数量',
    'exchange_total': '金额',
    'exchange_wallet': '钱包',
    'exchange_sell': '卖出',
    'exchange_buy': '买入',
    'exchange_determine': '确定',
    'exchange_price_ont': '价格不能为0',
    'exchange_price': '价格',
  },
  'public0': {
    'public124': '密码不匹配，请重新输入',
    'public244': '邀请码',
    'public219': 'PayPal',
    'public51': '已上架',
    'public52': '已下架',
    'public147': '暂无广告',
    'public140': '未完成订单',
    'public62': '剩余时间',
    'public208': '取消申诉',
    'public141': '暂无订单',
    'public155': '当前广告',
    'public156': '历史广告',
    'public44': '请选择地址或使用新地址',
    'public46': '请输入提现金额',
    'public47': '提现额度不能大于可用余额{0}',
    'public196': '请设置银行卡信息',
    'public198': '微信',
    'public197': '请设置微信账号及收款码，收付款更便捷',
    'public199': '支付宝',
    'public261': '请设置支付宝账号及收款码，收付款更便捷',
    'public218': 'PayPal收款',
    'public220': '请设置PayPal信息',
    'public221': 'PayPal账号',
    'public222': '请输入PayPal账号',
    'public107': '请输入证件ID',
    'public106': '请选择性别',
    'public214': '请上传支持格式的文件！',
    'public217': '请选择证件',
    'public90': '未选择文件',
    'public194_Low': '低',
    'public194_Medium': '中',
    'public194_High': '高',
    'public42': '解除绑定',
    'public78': '名字',
    'public114': '最小限额',
    'public115': '最大限额',
    'public136': '可接受的最高单价',
    'public116': '我要购买多少',
    'public112': '请输入币种数量',
    'public254': '发布广告确认',
    'public119': '购买数量必须大于等于{0}',
    'public133': '最大限额不能小于最小限额',
    'public110': '最小限额必须大于等于{0}',
    'public117': '我要出售多少',
    'public137': '可接受的最低单价',
    'public163': '请输入整数{0}~{1}',
    'public118': '请选择交易方式',
    'public186': '请输入好评率',
    'public113': '请输入单价',
    'public50': '暂无相关数据',

    "public130":"请输入有效的数字",
    "public109":"请登录后再发布广告",
    "public161":"发送",
    "public6":"请输入手机号",
    "public256":"当前价格",
    "public255":"下单确认信息",
    "public135":"请输入有效的银行卡号",
    "public249":"交易订单",
    "public250":"请输入内容",
    "public25":"已取消",
    "public24":"等待卖家放币",
    "public143":"新建交易",
    "public144":"请先付款",
    "public145":"等待放币",
    "public146":"完成交易",
    "public149":"卖家",
    "public148":"买家",
    "public65":"收款人",
    "public152":"待付款",
    "public154":"已付款",
    "public153":"备注信息",
    "public150":"等待付款",
    "public15":"请登录后再交易",
    "public251":"系统消息",
    "public183":"（1）错误的申诉会导致发起人好评率下降。申诉在受理前，发起人可根据需要主动取消申诉。",
    "public184":"（2）针对已经标记为已付款的订单，一方提交申诉后，交易双方可继续沟通释放数字币。",
    "public185":"（3）申诉一旦受理，系统将根据申诉内容，判断双方的欺诈行为，对欺诈方做出冻结、封禁等处理。",
    "public1":"问题类型",
    "public28":"耐心等待买家付款",
    "public29":"确认付款后，请尽快放币",
    "public288":"是否已检查账户并确实<strong>“收到款项”</strong>？",
    "public289":"<span style='color:rgb(255,147,0);'>警告：</span>一旦确认放币代币将转入他人账户，“代币将<strong>无法找回</strong>”。是否放币？",
  },
  'otc_exchange': {
    'otc_exchange_USD': '美元',
    'otc_exchange_want_buy': '我要买币',
    'otc_exchange_want_use': '我想',
    'otc_exchange_Trad_amount': '交易额',
    'otc_exchange_Upload': '上传',
    'otc_exchange_acceptable_minimum_price': '可接受最低单价',
    'otc_exchange_Bid': '对标交易所',
    'otc_exchange_Set_right': '马上设置',
    'otc_exchange_transaction_method': '交易方式',
    'otc_exchange_UNRELEASE': '未放币',
    'otc_exchange_ask': '单价',
    'otc_exchange_limited_price': '限价',
    'otc_exchange_username': '用户名',
    'otc_exchange_Payment_Method': '选择支付方式',
    'otc_exchange_SGD': '新币',
    'otc_exchange_price_float_rate': '对交易所价格的浮动比例',
    'otc_exchange_determine': '确定',
    'otc_exchange_each_other': '请评价对方',
    'otc_exchange_transactions_completed1': '已完成',
    'otc_exchange_Trading_limits': '交易限额',
    'otc_exchange_purse_see': '前往钱包查看',
    'otc_exchange_transactions_completed2': '交易{0}笔',
    'otc_exchange_phone': '手机号',
    'otc_exchange_Selling_price_set': '出售价设置',
    'otc_exchange_Successful': '交易成功！',
    'otc_exchange_delay': '申请延时',
    'otc_exchange_buy': '购买',
    'otc_exchange_Order_now': '立即下单',
    'otc_exchange_Scan_payment': '扫描支付',
    'otc_exchange_lowestPrice_sort': '以价格最低排序',
    'otc_exchange_Online': '在线',
    'otc_exchange_bid': '单价',
    'otc_exchange_complaint': '发起申诉',
    'otc_exchange_BADTRADING': '恶意买卖',
    'otc_exchange_prompt10': '价格设置',
    'otc_exchange_IDR': '印尼盾',
    'otc_exchange_need_pay': '您需付款',
    'otc_exchange_Good_rating': '好评率',
    'otc_exchange_AUD': '澳元',
    'otc_exchange_MYR': '马币',
    'otc_exchange_TIMEOUT': '长时间无回应',
    'otc_exchange_prompt7': '提交申诉后，申诉受理小组会有工作人员1个工作日内帮您核实处理',
    'otc_exchange_prompt8': '如有需要请上传相关凭证截图',
    'otc_exchange_prompt9': '交易数量',
    'otc_exchange_prompt3': '你想使用多少{0}',
    'otc_exchange_OTHER': '其它',
    'otc_exchange_prompt4': '下单后将冻结卖家数字资产',
    'otc_exchange_prompt6': '我已经同意并确认以上交易信息',
    'otc_exchange_EUR': '欧元',
    'otc_exchange_sell': '出售',
    'otc_exchange_HKD': '港币',
    'otc_exchange_TWD': '新台币',
    'otc_exchange_UNPAID': '买家并未付款',
    'otc_exchange_highestPrice_sort': '以价格最高排序',
    'otc_exchange_prompt1': '订单已锁定请你尽快支付',
    'otc_exchange_prompt2': '请至少设置一种付款方式',
    'otc_exchange_trading_login': '请先登录后再交易',
    'otc_exchange_ad_management': '我的广告管理',
    'otc_exchange_buys': '购买',
    'otc_exchange_price': '溢价后单价',
    'otc_exchange_want_sell': '我要卖币',
    'otc_exchange_SEK': '瑞典克朗',
    'otc_exchange_Confirmed_payment': '已确认付款',
    'otc_exchange_acceptable_maximum_price': '可接受最高单价',
    'otc_exchange_operating': '操作',
    'otc_exchange_credit': '信用',
    'otc_exchange_Payment_Management': '付款方式管理',
    'otc_exchange_sells': '出售',
    'otc_exchange_Credit_sort': '以信用最高排序',
    'otc_exchange_good_rating': '要求对手方好评率必须大于此设定值',
    'otc_exchange_Buy_all': '一键扫货',
    'otc_exchange_purchase': '返回购买列表',
    'otc_exchange_JPY': '日元',
    'otc_exchange_frequency': '交易次数',
    'otc_exchange_order_number': '订单编号',
    'otc_exchange_CNY': '人民币',
    'otc_exchange_THB': '泰铢',
    'otc_exchange_Email': '邮箱',
    'otc_exchange_Click_enlarge': '点击放大',
    'otc_exchange_KRW': '韩元'
  },
  'otc_legal': {
    'otc_legal_input_Alipay_number': '请输入支付宝账号',
    'otc_legal_input_WeChat_number': '请输入微信账号',
    'otc_legal_Bank_Transfer': '银行转账',
    'otc_legal_currency': '收款方式设置',
    'otc_legal_Aipay_code': '支付宝收款码',
    'otc_legal_Alipay_number': '支付宝账号',
    'otc_legal_Payee_Name': '收款人姓名',
    'oyc_legal_Bank_card': '银行卡',
    'otc_legal_input_Payee_Name': '请输入收款人姓名',
    'otc_legal_Upload_payment': '点击上传收款码',
    'otc_legal_cancel': '取消',
    'otc_legal_Alipay_receivables': '支付宝收款',
    'otc_legal_confirm': '确定',
    'otc_legal_save': '保存',
    'otc_legal_Name': '姓名',
    'otc_legal_Bank_number': '银行卡号',
    'otc_legal_Wechat_number': '微信账号',
    'otc_legal_input_bank': '请输入开户行',
    'otc_legal_Set': '设置',
    'otc_legal_WeChat_code': '微信收款码',
    'otc_legal_WeChat_nam': '请输入姓名',
    'otc_legal_Image_not_exist': '图片不存在',
    'otc_legal_input_bank_number': '请输入银行卡号',
    'otc_legal_Bank': '开户行',
    'otc_legal_WeChat_receivables': '微信收款'
  },
  'home': {
    'home50': '充值',
    'home49': '提现',
    'intro': '简介',
    'home08': '邮箱',
  },
  'shop': {
    'payment': '支付方式',
    'phone': '电话号码'
  },
  'message': {
    'msg_surplus': '剩余',
    'no_message': '暂无站内消息',
  },
  'otc_ad': {
    "otc_ad_Trading_order":"正在交易订单",
    "otc_ad_complete":"完成",
    "otc_ad_Trad_Type":"交易类型",
    "otc_ad_Order_completed":"已完成订单",
    "otc_edit_title":"修改{0}{1}广告",
    "otc_ad_BankPay":"银行卡支付",
    "otc_ad_Trad_currency":"交易币种",
    "otc_ad_change_payment":"切换支付方式",
    "otc_ad_exchange":"换取",
    "otc_ad_cancelled_order":"已取消订单",
    "otc_ad_confirm":"确认",
    "otc_ad_status":"状态",
    "otc_trade_notice8":"更详细的交易规范请查看：",
    "otc_ad_Order_status":"订单状态",
    "otc_payment_check":"买家已标记为“已付款”，请您核实钱款是否已到账，如已到账，请及时放币。",
    "otc_ad_WeChatPay":"微信支付",
    "otc_trade_tips":"交易须知",
    "otc_payment_confirm":"现在请确认是否已付款，如未付款请点击“取消”按钮，如已付款请点击“我已付款”按钮。",
    "otc_trade_notice4":"收款时请仔细核实，买方的付款账户实名信息与平台实名信息是否一致。卖方收到的资金非买方本人转账，请卖方原路退回。",
    "otc_ad_Minimum_limit":"最小限额",
    "otc_trade_notice5":"已取消订单，如已付款，请及时申诉，上传付款证明等资料，说明情况。",
    "otc_trade_notice6":"转账时请勿备注任何信息，以免付款被拦截。",
    "otc_trade_notice7":"卖方一定要及时查看账户，并确保对方付款到账后再释放代币，否则将造成不可挽回的损失。",
    "otc_ad_Praise":"好评",
    "otc_ad":"广告",
    "otc_ad_minute":"分钟",
    "otc_unreleased":"未放币",
    "otc_post_ad":"发布广告",
    "otc_ad_Continue_trading":"继续交易",
    "otc_post_title":"发布{0}{1}广告",
    "otc_trade_notice1":"取消订单超过3笔将禁止1天OTC交易。",
    "otc_ad_Premium":"溢价",
    "otc_trade_notice2":"当您需要离开电脑一段时间时，请下架您的广告，以免受到用户申诉。",
    "otc_trade_notice3":"下单买入后冒充已付款，卖方可申诉举报，一经查实将封禁交易。",
    "otc_ad_view_details":"查看详情",
    "otc_ad_prompt9":"交易成功！请评价买家",
    "otc_ad_prompt8":"释放代币",
    "otc_unit_price":"交易单价",
    "otc_ad_minimum_amount":"请输入最小限额",
    "otc_ad_prompt7":"对方已付款，确认到账后请释放代币",
    "otc_ad_Collection_currency":"收款币种",
    "otc_ad_only_online":"仅展示在线用户",
    "otc_edit_ad":"修改广告",
    "otc_ad_prompt1":"交易所价格",
    "otc_ad_Transactional_advertis":"交易广告发布",
    "otc_ad_cancel_order":"取消订单",
    "otc_ad_prompt6":"已锁定订单等待对方付款",
    "otc_ad_maximum_amount":"请输入最大限额",
    "otc_ad_prompt5":"请注意，发布「每则广告」将收取 {0}{1}，广告发布期限为两周，在此期间编辑广告不收取额外费用，广告将在到期后自动下架。（广告不限制交易次数，您可以依据需求随时调整广告内容）",
    "otc_ad_prompt4":"栏位留空代表不设最低单价，售价将根据对标交易所调整",
    "otc_ad_max_uncompleted_orders":"单个广告可同时存在的未完成订单最大数量",
    "otc_ad_prompt3":"「溢价」为基于市场价格的溢出比例设定适当的溢价比例能让您的广告报价处于合理范围",
    "otc_order":"OTC订单管理",
    "otc_ad_Alipay_pay":"支付宝支付",
    "otc_ad_Payment_method":"支付方式",
    "otc_ad_PayPal":"PayPal支付",
    "otc_ad_maximum_orders":"最大处理订单数",
    "otc_ad_Bad_review":"差评",
    "otc_ad_Order_user":"下单用户",
    "otc_cancel_ad":"下架广告",
    "otc_payment_warn":"如果您未付款，请不要点击“已付款”按钮，请不要违反交易规则。",
    "otc_ad_Maximum_limit":"最大限额",
    "otc_trade_specification":"OTC交易规范",
    "otc_ad_uncompleted":"未完成",
    "otc_ad_payment_period":"请输入付款期限",
    "otc_ad_completed":"已完成",
    "otc_ad_payment_amount":"付款金额",
    "otc_ad_Average":"中评",
    "otc_current_currency":"当前法币",
    "otc_ad_Trading_restrictions":"交易限额",
    "data_sources":"数据来自coinmarket",
    "otc_ad_cacel_time":"取消时间",
    "otc_ad_expiration_pay":"付款期限",
    "otc_ad_TPurchase_price":"购买价设置",
    "otc_order_details":"订单详情",
    "otc_ad_Order_amount":"下单金额",
    "otc_ad_management":"我的广告管理",
    "otc_others":"其他",
    "otc_ad_Order_Management":"订单管理",
    "otc_ad_end_time":"完成时间"
  },
  'usercontent': {
    'user71': '充币',
    'user70': '提币',
    'no-address': '没有地址',
    'user33': '请输入谷歌认证码',
    'user38': 'KYC认证',
    'user44': '您的KYC认证状态为：认证失败',
    'user43': '恭喜您!您的身份验证已通过！',
    'user42': '您的KYC认证状态为：已通过',
    'user41': '系统消息',
    'user48': '您还未通过认证。请<span class=\'f-c-main\'>提交</span>您的材料以完成认证',
    'user47': '您的认证正在确认中。一但认证通过我们将会通知您',
    'user46': '您的KYC认证状态为：认证中',
    'user45': '您提交的材料有错误。请<span class=\'f-c-main\'>重新提交</span>资料以再次验证你的身份。请确保您的资料和自拍照都是高分辨率并且真实无篡改',
    'user85': '您的KYC认证状态为：未认证',
    'user80': '资讯',
    'user84': '条款说明',
    'user83': '帮助中心',
    'user82': '交易',
    'user81': '关于我们',
    'user95': '条款说明',
    'user94': '帮助中心',
    'user93': '交易',
    'user92': '关于我们',
    'user79': '公告',
    'user55': '系统消息',


    "user26":"在您的手机上安装 「Google Authenticator」二次身份验证软件 （各大应用市场搜索下载即可）iPhone手机：在App Store中搜索Google Authenticator Android手机：在安卓应用市场中搜索“谷歌身份验证器”，或搜索Google Authenticator Windows Phone：在WP应用商店中搜索Google Authenticator",
    "user25":"步骤一：在手机上安装双重验证程序 GoogleAuthenticator",
    "user24":"谷歌认证器绑定",
    "user23":"下次设置",
    "user29":"提示：启用2FA后，将不会显示令牌。如果您有多台设备，请将您的账户令牌添加到所有账户，然后再单击启用。",
    "user28":"在“Google Authenticator (身份验证器)”应用程序中， 点击“添加新账户 (iOS 下是 + 号)”，然后选择“扫描条形码”，并将手机上的相机镜头对准左侧扫描该条形码。如果您无法扫描成功上图的条形码，您还可以手动添加账户，并输入<span style=\"color:#e74c3c\"><strong>左侧二维码下方的密钥</strong></span>。请勿删除此双重验证密码账户，否则会导致您无法进行账户操作；如果误删，您可通过重置密钥重新获取。",
    "user27":"步骤二：扫描二维码",
    "user32":"确定",
    "user31":"取消",
    "user30":"谷歌认证码",
    "user61":"谷歌验证码",
    "foot-policy":"隐私政策",
    "wallet-rule":"钱包使用条款",
    "use-rule":"使用条款",
  },
  'user': {
    'set': '设置',
    'verify': '未验证',

  },
  'public': {
    'navigation_logout': '退出',
  },
  'otc_public': {
    'otc_Next': '下一页',
    'otc_Previous': '上一页',
  },
  'about': {
    'slogen': '你最爱的名人币交易所！',
  },
  'referral': {
    'date': '日期',
    'invitation_code': '邀请码',
    'invitation_poster': '邀请海报',
    'important_notice': '特别注意：',
    'last_one_month': '最近一月',
    'share_to_friends': '点击分享给好友',
    'download': '下载到桌面',
    'text': '文字',
    'last_one_year': '最近一年',
    'invite_reward_nt_10': '10.NewtonXchange会严查重复的或者虚假账户，一经发现，将不会支付奖励。',
    'invite_reward_10': '10. Bitark会严查重复的或者虚假账户，一经发现，将不会支付奖励。',
    'invitation_link': '邀请链接',
    'gift_coupon': '奖券',
    'my_referral': '我的邀请信息',
    'poster': '海报',
    'referral_friends_count': '好友数',
    'referral_text_nt': 'NewtonXchange交易所注册就送50个平台币，实名再送50个，现价0.1美元一个。更有机会得百万大奖。',
    'end_date': '结束时间',
    'referral_way': '邀请方式',
    'invitation_rank': '邀请排行',
    'login_share': '您还未登录，请登录后与好友分享',
    'invite_reward_1': '1. 一旦您推荐的好友成功完成注册，实名认证，他将获得660BARK的注册奖励和880BARK的实名认证奖励。',
    'total': '合计',
    'invitation_status': '邀请状态',
    'today': '今天',
    'commission_value': '我的邀请奖励',
    'invite_reward_7': '7. 活动抽奖劵使用规则以官方活动的详细规则为准。抽奖随机数基于Bitcoin区块hash产生，代码将透明公开开源。',
    'invite_friends': '邀请好友',
    'invite_reward_6': '6. 邀请活动开启时间见活动海报。邀请奖励每周发放一次。',
    'commission': '奖励',
    'invite_reward_9': '9. 被推荐人必须使用您的邀请链接、二维码或者邀请码注册才可以。',
    'refunded': '邀请奖励',
    'copy': '复制',
    'invite_reward_8': '8. Bitark保留随时对邀请活动规则进行调整的权利，但是对您推荐的好友数量没有限制。',
    'invite_reward_3': '3. 您还将获得大量活动抽奖券奖励，每位M1：10张，M2：6张，M3：3 张。活动抽奖券会作为Bitark平台的糖果分发、手续费抽奖等活动的权重依据之一。 我们将每个月收取手续费的5%加入抽奖活动奖池。若本月收取1000BTC手续费，50BTC加入抽奖活动奖池。',
    'invite_reward_2': '2. 您也将获得代币奖励。奖励规则为：每位M1：200BARK，M2：100BARK，M3：50BARK。（M1-M3为下级好友的层级。）',
    'invite_reward_5': '5. 为回馈前期用户的支持，在邀请活动开始前注册的用户均将自动获得M1-M3好友各一个及相应的奖励。',
    'invite_reward_4': '4. 邀请奖励均无上限限制。',
    'start_date': '开始时间',
    'invitation_history': '邀请历史',
    'invite_reward_nt_6': '6.邀请活动开启时间见活动海报。邀请奖励每周发放一次。',
    'referral_link': '复制邀请链接',
    'invite_reward_nt_5': '5.为回馈前期用户的支持，在邀请活动开始前注册的用户均将自动获得M1-M3好友各一个及相应的奖励。',
    'referral_rule': '邀请活动规则',
    'invite_reward_nt_4': '4.邀请奖励均无上限限制。',
    'address': '充币地址',
    'invite_reward_nt_3': '3.您还将获得大量活动抽奖券奖励，每位M1：3张，M2： 2张，M3：1张。活动抽奖券会作为Newton平台的糖果分发、手续费抽奖等活动的权重依据之一。',
    'register_prize': 'Bitark交易所注册就送660个平台币，实名再送880个，现价XX元一个。更有机会得百万大奖。',
    'invite_reward_nt_2': '2.您也将获得代币奖励。奖励规则为：每位M1：15 ATN，M2：10 ATN，M3：5 ATN。（M1-M3为下级好友的层级。）',
    'deem_relevant': '由于市场环境的改变，欺诈风险的存在等原因，Bitark保留随时对活动邀请规则做出调整的最终解释权。',
    'invite_reward_nt_1': '1.一旦您推荐的好友成功完成注册，实名认证，他将获得50 ATN的注册奖励和50 ATN的实名认证奖励。',
    'program_rules': '邀请规则',
    'invite_reward_nt_9': '9.被推荐人必须使用您的邀请链接、二维码或者邀请码注册才可以。',
    'invite_reward_nt_8': '8.NewtonXchange保留随时对邀请活动规则进行调整的权利，但是对您推荐的好友数量没有限制。',
    'referral_programme': '邀请项目',
    'invite_reward_nt_7': '7.活动抽奖劵使用规则以官方活动的详细规则为准。抽奖随机数基于Bitcoin区块hash产生，代码将透明公开开源。',
    'share_to': '分享到',
    'referral_friends': '我的邀请好友',
    'referral_id': '我的邀请码',
    'registeration_time': '注册时间',
    'invitees_num': '邀请人数',
    'important_notice_nt': '由于市场环境的改变，欺诈风险的存在等原因，Newton保留随时对活动邀请规则做出调整的最终解释权。',
    'referral_title': '扫描二维码邀请好友'
  },
  'trade_record': {
    'transfer_record': '资金划转记录',
    'exchange_record': '币币成交记录',
    'trade_record_hide': '隐藏已取消记录',
    'trade_record_search': '搜索',
    'trade_record_market': '市场',
    'export_6m': '最近半年',
    'not_transfer_record': '暂无资金划转记录',
    'entrust_detail': '成交明细',
    'trade_record_type': '方向',
    'trade_record_currency': '币种',
    'trade_record_reset': '重置',
    'not_history_entrust': '暂无历史委托',
    'trade_record_buy': '买',
    'current_entrust': '当前委托',
    'export_onexport': '导出',
    'not_otc_record': '暂无OTC交易记录',
    'trade_record_all': '全部',
    'trade_record_repeal': '全部撤销',
    'trade_record_export': '导出报表',
    'not_current_entrust': '暂无当前委托',
    'export_3m': '最近三个月',
    'export_1m': '最近一个月',
    'export_all': '所有记录',
    'export_title': '导出历史记录',
    'my_trade_record': '交易记录',
    'export_choose': '请选择时间范围',
    'entrust_record': '委托记录',
    'trade_record_sell': '卖',
    'export_range': '时间范围',
    'otc_record': 'OTC交易记录',
    'trade_record_time': '时间',
    'history_entrust': '历史委托',
    'not_exchange_record': '暂无成交记录',
    'export_1w': '最近一周',
    'export_1y': '最近一年'
  },
  'error_code': {
    'LACK_MAILBOX': '缺少邮箱',
    'PARAMS_ERROR': '参数有误',
    'EMAIL_FORMAT_ERROR': '邮箱格式错误',
    'ORDER_CHECKED': '该订单已处理',
    'PASSWORD_ERROR_FIVE': '密码错误，您还有1次机会',
    'CERTIFICATE_EXPIRED': '证件已过期',
    'INVALID_CODE': '验证码失效',
    'invalid_totp': '需要谷歌验证码',
    'USER_INFORMATION_TIMEOUT': '获取用户信息超时',
    'CODE_EMPTY': '验证码为空',
    'LACK_MESSAGE': '缺少消息',
    'OLD_PASS_ERROR': '原密码错误',
    'PASSWORD_ERROR_TWO': '密码错误，您还有4次机会',
    'LACK_DELAY_TIME': '缺少延时时间',
    'ORDER_USER_OFFLINE': '该广告的用户已下线',
    'NO_LEGAL_AGE': '您未达到法定成年年龄',
    'VERIFY_SECOND_PASS': '您的实名认证已通过',
    'MARKET_NOT_EXISTS': '该市场不存在',
    'ORDER_APPLY_FAIL_NOT_USER': '申请延时失败，非该订单用户',
    'ORDER_ABNORMAL_FINISH': '订单异常，无法完成',
    'OTC_FROCE_RELEASE_FROM_SYMBOL': '代币已经被系统管理员释放',
    'NOT_GOOGLE_AUTH': '操作异常，未进行谷歌二次验证，提币失败！',
    'NOT_HOLDING_CARD_AS_REQUIRED': '未按要求手持写有Bitark和日期卡片',
    'AD_EXIST_ORDER': '该广告存在正在交易的订单',
    'AD_ACCOUNT_NOT_BALANCE': '该广告用户的账户存在异常无法交易',
    'EXCHANGE_PERMISSION_FROZEN': '币币交易权限已被冻结',
    'ORDER_CREATE_FAIL_MAX_PROCESS': '该广告已达最大订单数，请稍后下单',
    'SET_WECHAT_FIRST': '请先设置微信信息',
    'ENTRUSTMENT_CANCEL_FAIL': '委托取消失败，请重试',
    'TRANS_PASSWORD_ERROR': '交易密码错误',
    'AD_PAGE_SHOW_COUNT': '10',
    'EMAIL_OVER_LENGTH': '输入的邮箱长度超过限制',
    'BIND_SUCCESS': '绑定成功',
    'ORDER_NOT_TRADING': '当前订单不在交易状态，禁止再向对方发送消息',
    'REGISTER_TYPE_ERROR': '注册方式错误',
    'USER_FROZEN': '您的账号已被冻结，无法进行新的交易',
    'ORDER_HAD_PAID': '该订单已支付，请不要重复支付',
    'PAY_TYPE_UNMATCH': '支付方式不匹配，请设置对应的支付方式',
    'CHANGE_PASSWORD_SUCCESS': '为了您的资产安全，登录密码修改后24小时以内不允许提现。',
    'SHOULD_REQUEST_TOKEN': '重新请求token。',
    'AD_UPDATE_FAIL': '广告修改失败',
    'APPEAL_FAIL': '申诉失败',
    'USER_ENJOY_LOGIN_FAIL': '向enjoy用户登录失败，返回信息为null',
    'APPEAL_HANDLED_FAIL': '申诉处理失败',
    'OTC_USER_UNFROZEN': '用户已解冻',
    'SETTING_SUCC': '设置成功',
    'SUCCESS': '操作成功',
    'USERNMAE_EMPTY': '用户名为空',
    'NOTIFY_FAIL': '提醒失败，交易状态有误',
    'ORDER_PRICE_ERROR': '订单价格不合理',
    'PASSWORD_ERROR_ONE': '密码错误，您还有5次机会',
    'UPLOAD_SUCCESS': '上传成功',
    'DB_HANDLE_EXCEPTION': '数据库处理异常',
    'DELETE_SUCCESS': '删除成功',
    'USERNAME_OVER_LENGTH': '输入的用户名长度超过限制',
    'AD_SOLD_OUT': '该广告已下架',
    'GOOGLE_CELLPHONE_AUTH_FIRST': '请先进行谷歌验证或短信验证',
    'WITHDRAWAL_LIMIT': '不能少于提现额度',
    'SHOPS_LEVEL_FIRST': '请设置商家认证等级',
    'SYMBOL_LACK': '该币种余额不足',
    'ORDER_PAY_SUCCESS': '订单支付成功',
    'EMAIL_REGISTER_SUCCESS': '注册成功，请前往邮箱激活',
    'XRP_AMOUNT_ERROR': '提币金额只能精确到小数点后6位',
    'PRICE_NOT_EQUAL_FIXED_PRICE': '网络繁忙，请重试',
    'AD_FIX_PRICE': '请输入限价',
    'PLEASE_RELEASE_CURRENCY': '对方已付款，确认到账后请释放代币',
    'ORDER_ABNORMAL_CANCEL': '订单异常，无法取消',
    'PASSWORD_NOT_SAME': '输入的密码与确认密码不一致',
    'AD_SYMBOL_COUNT_ERROR': '购买币种数量必须大于等于每笔最大订单量',
    'VERIFY_SECOND_GOING': '您的实名认证已进入复审阶段',
    'LACK_CURRENCY_COUNT': '缺少法币金额',
    'ONLY_ADDRESS_5': '只保存5个地址！',
    'OTC_NEW_ORDER_BODY': '您的OTC有新的订单，请前往处理。',
    'USERNAME_OR_PASSWORD_FAIL': '用户名或密码错误',
    'EDIT_FAIL': '修改失败',
    'ENTRUSTMENT_CANCEL_FINISHED': '委托已完成或取消',
    'RELEASE_SUCCESS': '解绑成功',
    'GET_FAIL': '获取失败',
    'APPEAL_FAIL_ORDER_NOT_USER': '申诉失败，非该订单用户',
    'ORDER_TRADE_REMAIN_ERROR': '该广告余额有变更，请重新下单',
    'SUSPEND_TRADES_24H': '当天取消3次订单，将被暂停OTC交易24小时！',
    'ACCOUNT_ALREADY_LOCKED': '账户已被锁定，1小时后再试。',
    'SEND_CODE_FREQUENT': '验证码发送频繁',
    'XRP_TAG_BLANK': '请输入地址标签',
    'LACK_USER_ID': '缺少用户ID',
    'DETAIL_NOT_FOUND': '详情不存在',
    'VERIFY_NOT_PASS': '您的实名认证未通过，请重新填写和上传符合要求的个人信息。（每人仅有三次KYC机会）',
    'MAIL_SENT_FAILED': '邮件发送失败',
    'ID_PHOTO_UPLOAD_ERROR': '上传错误的证件照片',
    'USER_ENJOY_ALREADY_EXIST': '登录失败，该账号已注册，请联系客服人员。',
    'AD_SOLD_OUT_FIRST': '请先下架该广告',
    'LACK_ALIPAY_NUMBER': '缺少支付宝帐号',
    'WITHDRAW_FAIL_24TH': '重置密码后24小时内禁止提币',
    'BIND_ALREADY': '已绑定过',
    'FEEDBACK_FAIL': '意见反馈失败',
    'AD_EXIST': '该类型的广告已存在',
    'AD_BUY_SYMBOL_COUNT_ERROR': '购买币种数量不满足最小限额',
    'LACK_IMAGE_PATH': '缺少图片路径',
    'LACK_BENCH_MARKING': '缺少对标交易所',
    'TRANS_PASSWORD_FORMAT_ERROR': '交易密码格式错误',
    'ERROR_LENGTH': '长度错误',
    'BENCH_MARKING_SYMBOL_NULL': '暂无信息',
    'OTC_CANCEL_ORDER': '已经取消了交易订单。',
    'ORDER_DELETE_SUCCESS': '订单取消成功',
    'DISTRIBUTE_COMPLETE': '该记录已存在',
    'CONFIRM_PASSWORD_IS_NULL': '输入的确认密码为空',
    'ORDER_FINISH': '订单完成',
    'ACCOUNT_LOCK': '账号已被锁定，请联系客服',
    'LACK_SYMBOL': '缺少币种',
    'LACK_AD_ID': '缺少广告ID',
    'LACK_CARD_BANK': '缺少银行卡开户行',
    'NAME_OVER_LENGTH': '姓名长度超过限制',
    'BE_REGISTERED': '该手机号码已被注册',
    'CONFIRM_PASSWORD_FORMAT_ERROR': '确认密码格式错误',
    'SHOPS_APPLY_FAIL': '申请失败',
    'AD_MAX_COUNT_ERROR': '最大限额不能小于最小限额',
    'MAX_PROCESS_NUM_TIP': '不滿足最大处理数:5',
    'LACK_TRADE_TYPE': '缺少交易类型',
    'DOCUMENTS_NOT_HIMSELF': '非本人证件',
    'WITHDRAW_ADDRESS_INVALID': '无效的提现地址',
    'ALREADY_BEEN_TAKEN': '邮箱账号已被注册',
    'verify_email_required': '请先邮件激活账号',
    'LACK_CARD_NAME': '缺少银行卡姓名',
    'FROZEN_24': '封禁24小时',
    'AD_DELETE_FAIL': '广告删除失败',
    'ORDER_APPLY_FAIL_NOT_TRADING': '申请延时失败，该订单非交易中',
    'LACK_WECHAT_NAME': '缺少微信名',
    'SYMBOL_INEXIST': '该币种信息不存在',
    'TRANS_PASSWORD_NOT_SAME': '交易密码和确认交易密码不一致',
    'AD_MAX_CURRENCY_ERROR': '广告单笔最大金额不能大于其等级限额',
    'SET_BANK_FIRST': '请输入银行卡信息',
    'NICKNAME_LENGTH_ERROR': '输入的昵称长度不符合要求（2-20位字符）',
    'AMOUNT_ERROR': '金额错误',
    'ORDER_TRADE_TYPE_ERROR': '交易类型与广告类型不能一致',
    'LACK_CARD_NUMBER': '缺少银行卡号',
    'OTC_USER_FROZEN': '由于您取消了过多的订单，系统已暂停您24小时新的OTC交易。',
    'MAX': '超过最大值',
    'ACCOUNT_BALANCE_FAIL': '操作异常，交易失败',
    'USER_FORBID_LOGIN': '您的账户已冻结，无法登录',
    'ORDER_CREATE_FAIL': '订单新建失败',
    'AD_ORDER_FEE_LACK': '该币种余额不足，不够广告成交费',
    'PASSWORD_IS_NULL': '输入的密码为空',
    'MAXIMUM_BITS_8': '最多输入8位小数',
    'NUMERIC': '输入类型必须为数字',
    'SETTING_FAIL': '设置失败',
    'WITHDRAW_PERMISSION_FROZEN': '提现权限已被冻结',
    'UPLOAD_IMG_FAIL': '上传失败',
    'LACK_PRICE_TYPE': '缺少价定方式',
    'ORDER_OPPOSITE_MAX_COUNT': '对方未完成的订单已达最大交易数，请稍后再试',
    'ONLINE': '在线',
    'LACK_MAX_PROCESS_NUM': '缺少最大处理数',
    'IMAGE_TYPE_ERROR': '只支持png、jpg、jpeg、bmp格式图片',
    'OTC_PAY_FINISH': '已经标记确认付款，请查收。',
    'BIND_FAIL': '绑定失败',
    'AD_SELL_SYMBOL_COUNT_ERROR': '出售币种价值（出售币种数量 * 溢价后单价）必须大于等于最小交易限额',
    'NEO_AMOUNT_ERROR': '提币金额必须是整数',
    'TRANS_OLD_PASSWORD_ERROR': '旧交易密码错误',
    'RSA_PUBLIC_KEY_ERROR': '获取RSA公钥失败',
    'MOBILE_REGISTER_SUCCESS': '注册成功，请前往登录页登录',
    'WECHAT_IMAGE': 'wechat.jpg',
    'WITHDRAW_FAILED': '提现失败，请重试',
    'LACK_PAYPAL_NAME': '缺少paypal姓名',
    'ORDER_NUMBER_INVALID': '订单号无效',
    'RELEASE_CURRENCY_WARN': '您正在确认收款，释放代币，一旦确认，代币将转入他人账户，无法找回！',
    'SHOULD_REQUEST_CODE': '重新请求验证码。',
    'USER_NOT_EXIST': '用户不存在',
    'SERVER_BUSY': '系统繁忙，请稍后重试',
    'invalid_grant': '用户名或密码错误',
    'THE_FUND_PASSWORD_IS_INCORRECT': '资金密码错误',
    'ORDER_MAX_COUNT': '您未完成的订单已达最大交易数，请先完成部分订单',
    'OTC_PERMISSION_FROZEN': '您的OTC交易权限已被冻结',
    'FROZEN_72': '封禁72小时',
    'PASSWORD_ERROR_THREE': '密码错误，您还有3次机会',
    'SELLER_RELEASE_CURRENCY_WARN': '卖家已确认收款，并释放代币，请注意查收！',
    'EDIT_SUCCESS': '修改成功',
    'LACK_LEVEL': '缺少好评率',
    'AVAILABLE_INSUFFICIENT': '余额不足',
    'BAD_UD_LENGTH': '身份证长度错误',
    'COMMUNITY_ACCOUNT_INEXIST': '社区账户不存在',
    'SMS_CODE_INVALID': '短信验证码已失效',
    'ORDER_FORBID_SAME_USER': '订单禁止，买卖双方不能相同',
    'AD_CREATE_FAIL': '广告发布失败',
    'EOS_MEMO_BLANK': '请输入MEMO',
    'EOS_AMOUNT_ERROR': 'EOS提币金额只能精确到小数点后4位',
    'LACK_ORDER_NUMBER': '缺少订单号',
    'ORDER_HAD_CANCEL': '该订单已取消，请不要支付',
    'ORDER_NUMBER_FAIL': '订单号生成失败',
    'DIR_INEXIST': '目录不存在',
    'OTC_FORCE_DOWN_AD': '您的广告已被强制下架',
    'GOOGLE_AUTH_FIRST': '请先进行谷歌验证',
    'ORDER_COMMENT_FAIL_NOT_FINISH': '订单评论失败，该订单未完成',
    'SYMBOL_NOT_FOUND': '币种不能为空',
    'ORDER_DELETE_FAIL': '订单取消失败',
    'ADD_SUCCESS': '添加成功',
    'VERIFY_FIRST_GOING': '您的实名认证已进入初审阶段',
    'LACK_SYMBOL_COUNT': '缺少币种数量',
    'SMS_CODE_FORMAT_ERROR': '短信验证码格式错误',
    'DELETE_FAIL': '删除失败',
    'SETTING_SUCCESS': '设置成功',
    'AD_DOWN_SUCCESS': '广告下架成功',
    'UPLOAD_JPG': '请上传jpg格式',
    'ORDER_TRADE_GT_COUNT': '大于最大交易限额',
    'AD_DOWN_FAIL': '广告下架失败',
    'ORDER_APPLY_SUCC': '申请延时成功',
    'IMAGE_INVALID': '图片无效',
    'NO_RELEVANT_INFO': '未找到相关信息',
    'ID_NOT_FOUND': 'id不存在',
    'LACK_MARKING_ID': '缺少对标交易所ID',
    'LACK_QQ': '缺少QQ',
    'NOTHING': '暂不处罚',
    'LACK_COMMUNITY': '缺少社区',
    'WALLET_NOT_FOUND': '找不到钱包',
    'WRITE_MOBILE': '请填写手机号码',
    'LACK_PAY_TYPE': '缺少支付类型',
    'SYMBOL_AD_REMAIN_LACK': '广告剩余数量不足',
    'APPEAL_FAILED': '已被受理。您的申诉内容不属实。对您进行警告及处罚处理。处罚结果：',
    'MEMO_TOO_LONG': '备注最多只能输入100个字符',
    'MIN': '低于最小值',
    'ORDER_COMMENT_FAIL_NOT_USER': '订单评论失败，非该订单用户',
    'SMS_MOBILE_FORMAT_ERROR': '手机号码格式不正确',
    'IMAGE_INEXIST': '图片不存在',
    'LACK_MOBILE': '缺少手机号',
    'MIN_TRADE_COUNT_TIP': '不满足最小交易数量',
    'ORDER_NOT_USER': '非该订单用户',
    'INVALID_UD': '请输入有效的身份证号',
    'BIND_MOBILE_NOT_EXIST': '输入的手机号与绑定的手机号不符',
    'APPEAL_UNHANDLED': '申诉未处理，无法重新申诉',
    'OTC_UNLOCK_ORDER': '代币已经被系统管理员解锁，请查收。已经警告及处罚买方',
    'BUYER': '买家',
    'TWO_FACTOR_VERIFY_FAIL': '谷歌验证码错误',
    'MOBILE_AUTH_FIRST': '请先绑定短信验证',
    'OTC_NO_TITLE': '无标题',
    'TRANS_OLD_PASSWORD_FORMAT_ERROR': '旧交易密码格式错误',
    'TRANS_CONFIRM_PASSWORD_FORMAT_ERROR': '确认交易密码格式错误',
    'BE_APPEALED': '您已被申诉且存在违规操作。现对您进行警告及处罚处理。处罚结果：',
    'ORDER_APPLY_ONE': '申请延时失败，只能申请一次',
    'BUY': '买',
    'GET_SUCCESS': '获取成功',
    'NO_EXCHANGE_PRIVILEGE': '没有交易权限',
    'NOT_MOBILE_AUTH': '操作异常，未进行短信二次验证，提币失败！',
    'OTC_NO_BODY': '无内容',
    'WAIT_OPERATE': '网络繁忙，请稍后操作',
    'EXCEED_MAX_WITHDRAWAL_AMOUNT_COUNTS': '已超过今日快速提现额度或次数',
    'EXCHANGE_EXCEPTION': '交易异常',
    'EXPORT_OTC_FAIL': '导出报表失败',
    'LACK_MIN_AMOUNT': '缺少最小限额',
    'LOGIN_AGAIN': '请重新登录',
    'PASSWORD_CANNOT_SAME': '新密码与原密码不能相同',
    'APPEAL_CANCEL_SUCCESS': '申诉取消成功',
    'WITHDRAW_ADDRESS_FAIL': '不允许向交易所地址提现',
    'LENGTH_50': '请输入长度为1~50的字符',
    'ADDRESS_INPUT_ERROR': '请输入正确的地址',
    'OTC_FROCE_RELEASE_FROM_SYMBOL_BODY': '代币已经被系统管理员释放',
    'SEND_SMS_ERROR': '发送短信失败',
    'OTC_NEW_ORDER': '您的OTC有新的订单，请前往处理。',
    'AUTOMATICALLY_CANCEL': '由于您在规定时间内未标记确认付款，系统已经自动取消了您的订单！',
    'CODE_FAIL': '验证码错误',
    'OTC_FORCE_DOWN_AD_BODY': '您的广告已被强制下架',
    'AD_BUY_SYMBOL_COUNT_SMALL': '购买币种数量不能小于交易手续费',
    'NO_PAY_TYPE': '没有设置支付方式',
    'USER_INFORMATION_FAIL': '获取用户信息失败',
    'INTEGER': '输入类型必须为整型',
    'OTC_PAY_FINISH_BODY': '已经标记确认付款，请查收。',
    'CELLPHONE_AUTH_FIRST': '请先进行短信验证',
    'RESET_CODE_ERROR': '重置码错误',
    'ADD_FAIL': '添加失败',
    'OTC_USER_FROZEN_BODY': '由于您取消了过多的订单，系统已暂停您24小时新的OTC交易。',
    'CANCEL_ORDER_CONFIRM': '您正在取消交易订单，如果24小时内取消3笔，将被禁止OTC交易24小时！是否继续取消？',
    'ORDER_TRADE_COUNT_ERROR': '不满足交易限额',
    'EXPORT_OTC_SUCC': '导出报表成功',
    'WARNING': '警告',
    'CANNOT_BE_THE_SAME_AS_THE_LOGIN_PASSWORD': '资金密码不能和登录密码相同',
    'LACK_AD_TYPE': '缺少广告类型',
    'APPEAL_WIN': '已被受理。您的申诉内容属实。我们已经警告及处罚对方。',
    'VERIFY_CODE_IS_NULL': '输入的谷歌验证码为空',
    'LACK_PAYPAL_NUMBER': '缺少paypal账号',
    'RESETCODE_FAIL': '重置密码',
    'SYMBOL_WALLET_INEXIST': '请先设置默认钱包',
    'RELEASE_FAIL': '解除失败',
    'PASSWORD_FORMAT_ERROR': '密码格式错误',
    'SUBMIT_SUCCESS': '提交成功',
    'OLD_PASSWORD_IS_NULL': '输入的旧密码为空',
    'LACK_MAX_AMOUNT': '缺少最大限额',
    'CONFIRM_PASSWORD_LENGTH_ERROR': '输入的确认密码长度不符合要求（6-16位字符）',
    'CONFIRM_WITHDRAW_TIMEOUT': '提现确认已超时',
    'FROZEN_FOREVER': '永久封禁',
    'LOGIN_PASSWORD_ERROR': '登录密码错误',
    'KYC_AUTH_FIRST': '请先完成实名认证',
    'LACK_DESCRIPTION': '缺少描述',
    'LACK_WECHAT_NUMBER': '缺少微信号',
    'USER_REGISTER_EXCEPTION': '登录失败，账号注册异常：',
    'FILL_IN_THE_WRONG': '姓名或证件号码填写错误',
    'LACK_PAY_LIMIT': '缺少支付限时',
    'OTC_CANCEL_ORDER_BODY': '已经取消了交易订单。',
    'UPLOAD_IMG_SUCCESS': '上传成功',
    'SELLER': '卖家',
    'RELEASE_CURRENCY_CONFIRM': '是否确认放币？',
    'LACK_NAME': '缺少姓名',
    'APPEAL': '您的申诉订单',
    'CONFIRM_PAYMENT_RECEIPT': '卖方确认收款，已放币！请进行评价！',
    'APPEAL_HANDLED_SUCCESS': '申诉处理成功',
    'ORDER_UNPAID': '该订单未付款',
    'SET_PAY_TYPE_FIRST': '请先设置支付方式',
    'OTC_USER_AD_DOWN_BODY': '您的广告剩余数量不满足交易限额已被下架',
    'IDCARD_DUPLICATION': '您的身份证号已被使用',
    'ORDER_CREATE_SUCCESS': '订单新建成功',
    'SUB_NOT_RESUBMIT': '已提交，请勿重新提交',
    'KEY_INFORMATION_BE_COVERED': '关键信息被覆盖',
    'LACK_PARAMETER': '缺少参数',
    'ORDER_TRADE_LT_COUNT': '小于最小交易限额',
    'EXCEED_MAX_WITHDRAWAL_AMOUNT': '超过用户当日最大提现额度',
    'DEDUCTION_STATE_ERROR': '抵扣状态错误',
    'PASSWORD_LENGTH_ERROR': '输入的密码长度不符合要求（6-16位字符）',
    'TOTP_CANNOT_BE_EMPTY': '请输入谷歌验证码',
    'QUANTITY_ERROR': '数量错误',
    'OTC_FROCE_RELEASE_TO_SYMBOL': '代币已经被释放，请进行查收',
    'AD_DATE_OUT': '该广告已过期',
    'SEND_CODE_SUCCESS': '验证码发送成功',
    'USER_NOT_ACCOUNT': '找不到账户',
    'FAIL': '操作失败',
    'BUSINESS_LIMIT_CONTROL': '短信业务限流（每分钟只能发1条短信，每小时只能发5条短信，每天累计只能发10条短信）。',
    'SET_ALIPAY_FIRST': '请先设置支付宝信息',
    'APPEAL_SUCCESS': '申诉提交成功',
    'BIND_MOBILE_ALREADY_EXIST': '该手机号已被绑定，请更换其他的手机号。',
    'LIMIT_SELL_AMOUNT': '失败，需要买入更多ACM',
    'OTC_SYSTEM_CANCEL_ORDER_BODY': '订单超时未处理，已被自动取消。',
    'NOTIFY_SUCC': '提醒成功',
    'SHOPS_APPLY_AGAIN': '不要重复申请',
    'ORDER': '您的订单',
    'LACK_COMMENT_TYPE': '缺少评价',
    'USERNAME_IS_NULL': '输入的用户名为空',
    'USER_ALREADY_EXIST': '用户已存在',
    'OTC_SYSTEM_CANCEL_ORDER': '订单超时未处理，已被自动取消。',
    'IDCARD_OVER_LENGTH': '身份证号长度超过限制',
    'CONFIRM_PAYMENT': '买方已经标记确认付款，请查收！',
    'ORDER_APPLY_FAIL': '申请延时失败',
    'AD_DELETE_SUCCESS': '广告删除成功',
    'PHOTO_NOT_DISTINCT': '照片不清晰或不完整',
    'USER_ACCOUNT_NOT_BALANCE': '下单用户的账户存在异常无法交易',
    'APPEAL_HANDLED': '申诉已处理，无法取消',
    'LACK_ALIPAY_NAME': '缺少支付宝名',
    'SHOPS_AUTH_FIRST': '需要认证商家才能发布广告',
    'ORDER_SYMBOL_NOTSAME': '买卖币种不一致',
    'MIN_TRADE_SUM_TIP': '不满足最小交易金额',
    'SELL': '卖',
    'PAYMENT_TIMEOUT_REMIND': '您的付款确认时间还剩5分钟，5分钟后系统将自动取消订单！请付款并标记确认付款！',
    'ORDER_COMMENT_EXIST': '订单已评论，不能重复评论',
    'LACK_TYPE': '缺少申诉类型',
    'NOT_ACTIVE': '用户没有激活',
    'Server_Error': '请求无响应，请稍后重试',
    'KYC_AUTH_FINISH': '已完成实名认证',
    'CODE_SUCCESS': '验证码正确',
    'LOAD_FINISHED': '已经全部加载完毕',
    'OTC_USER_AD_DOWN': '您的广告剩余数量不满足交易限额已被下架',
    'OTC_UNLOCK_ORDER_BODY': '代币已经被系统管理员解锁，请查收。已经警告及处罚买方',
    'NOT_FIND_USER': '找不到用户',
    'SERVER_REQUEST_TIMEOUT': '服务器请求超时，请重试',
    'ORDER_APPLY_FAIL_EXIST': '申请延时失败，已达延时最大次数',
    'TRANSACTION_FEE_NOT_CONFIG': '该交易账号的手续费没有配置',
    'VERIFY_CODE_LENGTH_ERROR': '输入的谷歌验证码长度超过限制',
    'VERIFY_FIRST_PASS': '您的实名认证已通过初审',
    'IMAGE_EXCEED_2': '图片不能超过2M',
    'IMAGE_EXCEED_1': '图片不能超过1M',
    'PASSWORD_ERROR_FOUR': '密码错误，您还有2次机会',
    'codeSuccess': '验证码发送成功',
    'PHONE_NUMBER_FORMAT_ERROR': '手机号格式错误',
    'OLD_PASSWORD_LENGTH_ERROR': '输入的旧密码长度不符合要求（6-16位字符）',
    'FROM_USER_FROZEN': '对方的账号已被冻结，无法进行新的交易',
    'NICKNAME_IS_EXISTS': '昵称已存在',
    'AD_UPDATE_SUCCESS': '广告修改成功',
    'APPEAL_FAIL_ORDER_UNPAID': '申诉失败，该订单未支付',
    'ORDER_COMMENT_SUCCESS': '订单评论成功',
    'OFFLINE': '离线',
    'LACK_CURRENCY': '缺少法币',
    'ACCOUNT_NOT_BALANCE': '您的账户存在异常已被锁定',
    'SYSTEM_ACCOUNT_INEXIST': '系统账户不存在',
    'NICKNAME_IS_NULL': '输入的昵称为空',
    'SMS_CODE_ERROR': '短信验证码错误',
    'TOKEN_INVALID': 'token失效，用户不存在',
    'SET_PAYPAL_FIRST': '请先设置Paypal信息',
    'SERVER_ERROR': '请求无响应，请稍后重试',
    'ALIPAY_IMAGE': 'alipay.jpg',
    'ORDER_EXIST_UNPAID': '您在该广告存在未付款的订单，请先付款！',
    'OTC_FROCE_RELEASE_TO_SYMBOL_BODY': '代币已经被释放，请进行查收',
    'AD_CREATE_SUCCESS': '广告发布成功',
    'ORDER_MIN_TRADE': '当前交易额小于最小订单数额',
    'FEEDBACK_SUCCESS': '意见反馈成功',
    'OTC_RELEASE_SYMBOL': '已确认收款，释放代币，请查收。',
    'SHOPS_APPLY_SUCCESS': '申请成功',
    'EMAIL_IS_NULL': '输入的邮箱为空',
    'PASSWORD_ERROR': '密码错误',
    'REPEAT_COMMIT': '请勿重复提交',
    'ORDER_ABNORMAL_PAID': '订单异常，无法支付',
    'OTC_USER_UNFROZEN_BODY': '您已解冻，可进行新的OTC交易',
    'OTC_RELEASE_SYMBOL_BODY': '已确认收款，释放代币，请查收。'
  },
}
