export default {
  'gcox_otc': {
    'P2P_swop': 'P2P交换',
    'max': '最大值',
    'you_want': '您想要 <span class="{0}">{1}</span> {2} ？',
    'buy': '购买',
    'sell': '出售',
    'build': '创建您的{0}广告',
    'sell_price': '售价',
    'buy_price': '买价',
    'now_buy': '立即购买',
    'now_sell': '立即出售',
    'otc_describe': 'OTC是一个强大而无缝的交易平台，可以连接法定和加密的世界。',
    'otc_app': 'OTC移动应用程序',
    'when_where': '无论何时何地交易！',
    'want': '想要{0}',
    'better_price': '想要更好的价格？',
    'get_cny_in_china': '卖比特币通过中国在中国到huzhengguo获得CNY',
    'advertising_details': '广告详情',
    'pay_to': '付给',
    'limit_number': '限制数量',
    'payment_method': '付款方式',
    'address': '地点',
    'pay_window': '付款窗口',
    'base': '基本',
    'detail': '详细',
    'i_want': '我想要',
    'new_advertising': '创建新的广告',
    'control_panel': '控制面板',
    'overall': '总体',
    'P2P_deal': 'P2P交易',
    'your_sell_advertising': '你的销售广告',
    'your_buy_advertising': '你的购买广告',
    'appraisement': '估计资产价值',
    'you_advertising': '你的广告',
    'show_all_symbol': '显示所有货币',
    'fee': '存款费用',
    'explain': '此押金地址只接受{0}。不要发送其他硬币。',
    'symbol_address': '比特币地址'
  }
}
